# Docker-compose for Graylog
version: '2'
services:
  mongodb:
    image: mongo:3
    #command: "mongod --config /conf/mongo.conf"
    volumes:
      - mongo_data:/data/db
#      - "./mongo:/conf/"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #ES_MAX_MEM: 1g
    ports:
     - "9200:9200"
     - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1536m
    
    
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog2/graylog:3.2
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: Bgw7mYROifuwMCojIcuQ0PYCiuwtOWNSIQBV6fbIfNIzpFFxKrVcRDOxJOPBmjHPhOA5uT928Ll9LlfpPEWxsy9a4VSgZebo
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - ${WEB_PORT:-9000}:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      #GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      #GRAYLOG_MONGODB_URI: mongodb://mongodb.service/graylog
      #GRAYLOG_MONGODB_MAX_CONNECTIONS: 100
      #GRAYLOG_MONGODB_THREADS_ALLOWED_TO_BLOCK_MULTIPLIER: 5
      #GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: graylog
    
    links:
      - "elasticsearch:elasticsearch"
      - "mongodb:mongodb.service"

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
